api_platform:
    title: Rentline API
    version: 1.0.0
    defaults:
        normalization_context:
            skip_null_values: false
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        json: ['application/json']
    enable_entrypoint: false
    enable_docs: true

